classDiagram{
    class Controller{
        +renderViewPage()
        +renderDashboard()
        +renderAnalisePage()
        +renderPutPage()
        +renderErrorPage()
        +sendAthlete()
        +sendCSV()
        +getKnnMetrics()
        +getCSV()
        +startApp()
    }
}